version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    
    environment:
      MYSQL_DATABASE: moviereservation
      
      MYSQL_ROOT_PASSWORD: ALFANETWORK
      
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./moviebooking
    restart: on-failure
    
    ports:
      - 6868:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/moviereservation?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ALFANETWORK 
      
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: